### PR TITLE
[framework] ImageUploadType now can be used for uploading specific image types

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Need to upload multiple types of images for Product
|New feature| Yes 
|BC breaks| No 
|Fixes issues| ... 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by boris-brtan** [comment]
Hello guys what is the progress?

**Comment by boris-brtan** [comment]
any progress so far?

**Comment by TomasLudvik** [comment]
Hello @vitek-rostislav,

I have updated my PR description, I did not know this will lead to such delay with accepting this PR. Sorry for that.

**Comment by vitek-rostislav** [comment]
Hi @TomasLudvik, thank you. The delay is my fault, I did not add the task to our sprint. I am adding it there now, so another colleague will review it and test it soon :wink:

**Comment by TomasLudvik** [comment]
Hi @vitek-rostislav, these are good news! Thank you!

**Pull request merged**
