### PR TITLE
[shopsys] docs: describe the conflict of firewalld with docker

### PR DESCRIPTION
**Pull request by henzigo**
taken from https://docs.docker.com/v1.6/installation/centos/#installing-docker-centos-7

| Q             | A
| ------------- | ---
|Description, reason for the PR| In Installation guide for production should be information about conflict firewalld with docker after restart firewall.
|New feature| No 
|BC breaks| No 
|Fixes issues| 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by henzigo** [comment]
Information was taken over https://docs.docker.com/v1.6/installation/centos/#installing-docker-centos-7

**Comment by boris-brtan** [comment]
THX, for the info.
if it is about docker chain, in the cofiguration there is set
`firewall-cmd --permanent --direct --add-chain ipv4 filter DOCKER` so after firewall restart it will recreate this chain.
I tried this on server and after firewall restart everything seemed to work. But maybe there could be some configuration requirements which can have problems.
Can you provide us with some use cases? or can we arrange some quick meeting about this issue?

**Comment by henzigo** [comment]
Sorry, I am confused. I gave you link to official documentation where they highlight the problem. So i do not understand why I have to provide use case with this problem. 

If you do not believe in official documentation, you can try `systemctl status firewalld -l` on your production server. You should see something like this:

```
firewalld[497]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 192.168.0.4 -d 192.168.0.4 --dport 8080 -j MASQUERADE' failed: iptables: No chain/target/match by that name.
firewalld[497]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 8000 -j DNAT --to-destination 192.168.0.4:8080 ! -i br-710051d83031' failed: iptables: No chain/target/match by that name.
firewalld[497]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-710051d83031 -o br-710051d83031 -p tcp -d 192.168.0.4 --dport 8080 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
```

**Comment by boris-brtan** [comment]
Some update when we implented 2 CIs and we found that without the part from documentation docker doesnt work due to firewall but if we apply the part from documentation it is OK so i think we have it OK and the logs are just logs. 
The main issue is that we do not have to restart `docker` service. If you have more info for this please provide us with it and we will test it, whether the restart of docker will be needed but it will cause only the problems to restart the whole docker service and its nodes.

**Pull request closed without merging**
