### PR TITLE
[project-base] Automatically delete sessions after 7 days of user inactivity

### PR DESCRIPTION
**Pull request by stanoMilan**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Session were never deleted from Redis and this caused some high disk space usage. This is fixed by this PR.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

Delete a session after 24 hours of user inactivity, because the session stays on the server forever and takes up memory space.

### CODE REVIEW

**Comment by henzigo** [comment]
That's not true. Sessions are deleted after 30 days. See https://github.com/shopsys/shopsys/blob/6b54709e620b80b27ad309c70c5457fcd737b817/project-base/config/packages/security.yaml#L66

**Comment by pk16011990** [comment]
@henzigo, `remember_me` is performed by cookie and it is not depend on session, or how do you mean it?

**Comment by grossmannmartin** [comment]
This should work (including remember me feature)
Admin will be forced to log again into administration after 24hours of inactivity even when he does not close the browser window.

**Comment by pk16011990** [comment]
@s3tezsky why :-1: ? It is realy problem for production eshops, because it creates records in redis to forever (and it requires RAM). Please explaint it to me.

**Comment by henzigo** [comment]
Hello, could you merge this PR? Sessions in Redis may increase more than 10GB of RAM after some time in running production because of this

**Comment by stanoMilan** [comment]
@TomasLudvik  for the old session does not set the  TTL to 604800  but this sessions remains set to -1(for all time ).

**Comment by s3tezsky** [comment]
> @s3tezsky why 👎 ? It is realy problem for production eshops, because it creates records in redis to forever (and it requires RAM). Please explaint it to me.

Just wanted to bring more attention here.
At first I thought we may reduce size of session first. After some digging I find out they are pretty small.

**Pull request merged**
