### PR TITLE
fix inconsistent line separators (changed to \n)

### PR DESCRIPTION
**Pull request by PetrHeinz**
Done automatically in the whole project via PhpStorm (via the "Inconsistent line separators" inspection).

Someone in the team probably doesn't have the git setting `core.autocrlf = input` as recommended.

The `PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineEndingsSniff` we use as a part of PSR-2 checks only PHP files during `phing standards`. We should probably have an automatic check for this...

| Q             | A
| ------------- | ---
|Description, reason for the PR| An inconsistency in line endings seen in UPGRADE.md
|New feature| No 
|BC breaks| No 
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
Hi, good catch :+1: We will resolve this PR in the current sprint and during this, we should create a new user story or issue for the automatic check. Also, we should find the person with incorrect git setting and make him fix it :slightly_smiling_face:

**Comment by TomasVotruba** [comment]
What needs to be done here to merge? It looks like is forgotten

**Comment by vitek-rostislav** [comment]
Hi @TomasVotruba, as always, it is all about priorities. Somebody from the team needs to review it, I thought this would be done in the previous sprint but we did not make it as there were more important things to do...But I will make sure it will be resolved this week :slightly_smiling_face:

**Comment by vitek-rostislav** [comment]
US in our internal backlog for sniff&fixer - https://app.yodiz.com/plan/pages/detail.vz?cid=10273#/us-4692

**Pull request merged**
