### PR TITLE
[shopsys] Upgraded yaml standards package

### LINKED ISSUE #1037: Inconsistent aliasing of Symfony services (missing standard in services.yml)
### What is happening

In `services.yml` configuration we use two different notations for defining service aliases:

```yaml
    Shopsys\FrameworkBundle\Model\Advert\AdvertFactoryInterface:
        alias: Shopsys\FrameworkBundle\Model\Advert\AdvertFactory
```

and

```yaml
    Shopsys\FrameworkBundle\Model\Advert\AdvertFactoryInterface: '@Shopsys\FrameworkBundle\Model\Advert\AdvertFactory'
```

which is inconsistent and may be confusing. The two notations work exactly the same way (see [Symfony docs on Aliasing](https://symfony.com/doc/3.4/service_container/alias_private.html#aliasing)).

### Expected result

We use only one of these notations and there is a fixer in `shopsys/coding-standards` for easier future maintenance.

I would suggest using only the longer expanded notation as it is easier to read and understand what's going on, even if it's a bit longer.

### PR DESCRIPTION
**Pull request by sspooky13**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Upgraded package for yaml standards, added standard for long definition of services overriding and newlines for yaml files.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1037
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by sspooky13** [comment]
P.S.: don't forget close https://github.com/shopsys/shopsys/pull/1412 if you accept 3. or 4. commit 😊

**Comment by pesektomas** [comment]
Hello @sspooky13, we updated your yaml-standard library in #1704  (18b25bd995122c31eafde06e4bc36de772ef0c76). But with olny one rule (YamlIndentChecker). You addded next two rules. One of rule is YamlEmptyLineAtEndChecker - it is ok for me, but I don't like the second rule - YamlServiceAliasingChecker. I ropened issue #1037 and I would like to wait for more opinions.

**Comment by sspooky13** [comment]
Hello @pesektomas, my library allow you to use [short syntax](https://github.com/shopsys/shopsys/pull/1552/commits/2b380bf2c0e4705cd665ebc47a92fc84f194bbe9) or [long syntax](https://github.com/shopsys/shopsys/pull/1552/commits/8a1a6f09cb5becadc76945a6b446f55a2490921f) so it's only your decision what you want to use 😊 
In my opinion, I don't care because of that library will fix it

**Comment by TomasLudvik** [comment]
> Nice job done here. I am just missing upgrade notes.

fixed

**Pull request merged**
