### PR TITLE
[framework] remove unnecessary passing parameter as a reference

### PR DESCRIPTION
**Pull request by pk16011990**
| Q             | A
| ------------- | ---
|Description, reason for the PR| [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Yes 
|Fixes issues| ... 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by PetrHeinz** [comment]
Hi @pk16011990 and thanks for the simplification. All pull requests with BC breaking changes must be rebased on the next major version branch (now `8.0`) and targeted against it (not `master`). You can change the target branch of you PR.

Also, for all BC breaking changes there must be an upgrade note (for this change it should be in `docs/upgrade/UPGRADE-8.0.0.md` under `shopsys/framework` in the *Application* section) so developers know what to do during the upgrading.

**Comment by pk16011990** [comment]
Hi, thanks for the explanations.

I rebased it onto `8.0`, but I'm not sure with upgrade notes. Something like "Hey, two methods has changed their interfaces, please check it" sounds weird.

**Comment by PetrHeinz** [comment]
@pk16011990 Thanks for the rebase. Writing upgrade notes can be hard. Here you've basically changed only the signatures of protected methods, so I'd say something along the way of:
```markdown
- check the usage of protected methods of `ParameterFilterRepository` if you've extended it in your project ([#1044](https://github.com/shopsys/shopsys/pull/1044))
    - the signatures of protected methods changed to remove the need of passing a parameter as a reference
```

**Comment by vitek-rostislav** [comment]
Hi @PetrHeinz, I have just noticed one more thing, could you please review the fixup commit? :innocent:

**Pull request merged**
