### PR TITLE
[framework] Solves issue: Difficult to add icon into submit button #161

### PR DESCRIPTION
**Pull request by kulincz**
| Q             | A
| ------------- | ---
|Description, reason for the PR| There is no easy way how to add an icon to an submit button
|New feature| Yes/No 
|BC breaks| Yes/No 
|Fixes issues| #161
|Standards and tests pass| Yes/No
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes/No

### CODE REVIEW

**Comment by Miroslav-Stopka** [comment]
Hi @kulincz,
thank you for this improvement. I have tried to test it but the result was not as expected.

`        {{ form_widget(form.add, {label: 'Add to cart'|trans, attr: {class: 'btn--success  btn--large btn--with-icon btn--with-icon-right svg-phone'}}) }}
`
With this configuration, I expect the icon to appear to the right. The reality is

image


Can you check it? Thank you :)

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, I see the problem, you have to use `btn--with-icon--right` instead of yours `btn--with-icon-right` :slightly_smiling_face: I made exactly the same mistake when I was testing it :smile:

**Comment by Miroslav-Stopka** [comment]
Problem is, the documentation says `btn--with-icon-right`, so Im not sure if I am mistaken or documentation is.

**Comment by vitek-rostislav** [comment]
Oh, I have overlooked it, my bad :man_facepalming: Thaks for noticing, it is fixed now :+1:

**Comment by Miroslav-Stopka** [comment]
Perfect :) Seems fine now. Review and tests - done. Good job both of you (@kulincz, @vitek-rostislav)

**Pull request merged**
