### PR TITLE
[shopsys] stop of services_test.yml maitenance 

### PR DESCRIPTION
**Pull request by pk16011990**
| Q             | A
| ------------- | ---
|Description, reason for the PR| functional tests sometimes fails with weird error after overriding of part of SSFW. Solition was annoying maintaining of services_test.yml
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes 
|Fixes issues| #907 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by TomasLudvik** [comment]
Hello, @pk16011990 is this still issue? After updating to Symfony 4 this should be already solved, right?

**Comment by TomasLudvik** [comment]
Ok I have discussed this with @pk16011990 and have some more information about this:
- first of all @pk16011990 does not think that everything has been solved, because there is many services left in `services_test.yaml` file, that has been removed in this PR. I think that needs some thorough investigation to find reasons why they are still there and if some needs to be kept add some comments describing why, so it is not subject of discussion in future.
- excluded services are present in this PR only because when they are registered via autodiscovery, `PublicServicesForFunctionalTestsCompilerPass` marks them as public an in such case they are not removed while Symfony optimizes container by removing unused services.

I would suggest as written at beginning, to investigate services_test.yaml and decide:
- which services can be removed
- which services has to be kept and add comment why it is that way

**Comment by pk16011990** [comment]
> * which services can be removed

All what I removed in this PR... All tests pass, App works... what more is it needed?

**Comment by TomasLudvik** [comment]
Hello @pk16011990, the milestone is set for this PR, so it will be merged before release of 9.1.0.

**Comment by TomasLudvik** [comment]
After discussion with @pk16011990 I am closing this PR as #1957 solves this using Symfony test container

**Pull request closed without merging**
