### PR TITLE
[shopsys] moved link to dev workflow instruction from contribution section back to introduction

### PR DESCRIPTION
**Pull request by PetrHeinz**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Goals of this document are to describe possible way to develop your project. This does not belong to the contribution at all. Even second requirement is `project-base` which is not requirement for contribution. Reverts shopsys/shopsys#893.<br />Thanks to @TomasLudvik for reporting in https://github.com/shopsys/shopsys/pull/893#issuecomment-493011864 :+1: and sorry for the mistake! Next time please suggest the revert yourself - it's just one click of a button right next to the merge commit (see the screenshot below).
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| ... 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

image

### CODE REVIEW

**Comment by TomasLudvik** [comment]
Hello @PetrHeinz, thank you for this PR. I wanted to start discussion before creating PR. We might consider renaming of this article or moving it so some other section, what do you think?

**Comment by PetrHeinz** [comment]
@TomasLudvik Why? Do you have any suggestions?

**Comment by TomasLudvik** [comment]
@PetrHeinz well you and @LukasHeinz have been confused by it and moved it to contributing. That is why I guess that not everything about this article is 100% clear and maybe we can somehow improve it, like: Shopsys Framework development workflow - possible way to develop your project?

**Comment by PetrHeinz** [comment]
Maybe *"Recommended Development Workflow"*?

**Comment by TomasLudvik** [comment]
@PetrHeinz I am not sure if it is really recommended or not :)

**Comment by TomasLudvik** [comment]
Hello @PetrHeinz this PR has been stale for a while, can we decide title for article and push it forward?

**Comment by PetrHeinz** [comment]
Considering we haven't managed to decide yet, I would leave it named *Shopsys Framework Development Workflow*.

There are some other titles that crossed my mind:
- Recommended Development Workflow
- Development Workflow
- Development Workflow on Shopsys Framework
- Development Workflow of Project on Shopsys Framework

If we can have consensus o nwhat title is best, I'd rename it. Otherwise, I'd let it be and only moved the link (as originally suggested in the PR). Maybe @vitek-rostislav can help.

**Comment by vitek-rostislav** [comment]
Hi guys, well the current title is a little bit confusing, indeed. I like "Recommended Development Workflow", or "Development Workflow of Project on Shopsys Framework" :wink:

**Comment by PetrHeinz** [comment]
@vitek-rostislav I'm in favor of *Development Workflow of Project on Shopsys Framework* when picking from these two, even if it is a bit of a mouthful... I wouldn't mind choosing the second one though.

@TomasLudvik Please, let's resolve this - what's your opinion on this?

**Comment by TomasLudvik** [comment]
@PetrHeinz and @vitek-rostislav I like any of suggested, maybe I would stay short and pick "Development Workflow" but any other is okay with me :)

**Pull request merged**
