### PR TITLE
[project-base] services.yml: automatic registration of classes with suffix "Repository" in namespace ShopBundle\Model\

### PR DESCRIPTION
**Pull request by Miroslav-Stopka**
| Q             | A
| ------------- | ---
|Description, reason for the PR| This modification is needed on every implemented project with at least one repository class in ShopBundle. Mentioned in #591 as well.
|New feature| No
|BC breaks| No
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by PetrHeinz** [comment]
In the `FrameworkBundle` we autoregister all classes in the Model namespace (also Component and DataFixture) with these suffixes: `Calculation`, `Facade`, `Factory`, `Generator`, `Handler`, `InlineEdit`, `Listener`, `Loader`, `Mapper`, `Parser`, `Provider`, `Recalculator`, `Registry`, `Repository`, `Resolver`, `Service`, `Scheduler`, `Subscriber` and `Transformer`.

Are you sure that `Repository` is the only one we should add?

**Comment by Miroslav-Stopka** [comment]
1) This is the only one I know is needed for sure. 

2) Truth is Im not happy with this random group of suffixes - Calculation, Facade, Factory, Generator, Handler ... Why? For example, I created new Loaded in ShopBundle and this one has not registered automatically. So I ve searched where is registered DataFixtureLoader in FrameworkBundle - found nothing. And then, after a longer period, I have found out that there exists some **unspecified**  group of classes, that is registered automatically because of suffixes :/

**Comment by PetrHeinz** [comment]
My point is that we shouldn't add these auto-discovered types of classes on one-by-one basis because every change generates an upgrade note - some work for the users to do.

We should probably make a list of all suffixes we want to set up the auto-discovery for, implement it and document it.

Maybe we should auto-discover `Facade`, `Factory`, `Repository` and `Service` because those class types are covered in [Basics About Model Architecture](https://github.com/shopsys/shopsys/blob/v7.0.0-beta2/docs/introduction/basics-about-model-architecture.md) (the article could be extended with a note about the auto-discovery).

**Comment by vitek-rostislav** [comment]
I do agree with your last comment, @PetrHeinz, however, should we really block this PR from merging because of that? :slightly_smiling_face:

**Comment by PetrHeinz** [comment]
@vitek-rostislav: Probably not.

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, could you please rebase your branch onto current master?

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, I have resolved the conflicts using Github web UI (it created the new commit that merged the master branch into your branch.) Now I will wait for tests on CI and validation with @LukasHeinz. If everything is ok, I will merge it using "Squash and merge" :wink:

**Comment by Miroslav-Stopka** [comment]
Hi @vitek-rostislav, @PetrHeinz,

thank you both of you :)

**Pull request merged**
