### PR TITLE
[shopsys] Remove unused dependencies and attributes

### PR DESCRIPTION
**Pull request by pk16011990**
| Q             | A
| ------------- | ---
|Description, reason for the PR| removed unused dependencies and attributes to make the code cleaner
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by s3tezsky** [comment]
Thanks @pk16011990  for PR!

I am really suprised how many dependencies are dead.
It would be great to add [phpstan rule for detecting dead code](https://github.com/slevomat/coding-standard#cleaning---detecting-dead-code) with this cahange too.

**Review by TomasLudvik — CHANGES_REQUESTED** [review]
As @s3tezsky suggested, it would be nice to introduce checks for this so it will be checked automatically in the future. I found this could be implemented https://psalm.dev/docs/running_psalm/configuration/#findunusedvariablesandparams

**Comment by grossmannmartin** [comment]
> As @s3tezsky suggested, it would be nice to introduce checks for this so it will be checked automatically in the future. I found this could be implemented https://psalm.dev/docs/running_psalm/configuration/#findunusedvariablesandparams

I tried Psalm, but it seems like it needs some work to configure it to match our needs – I get almost 7000 errors just after installation.

Also, I'm not sure how to perform such checks automatically... It's not always possible to delete it (due to bc promise for example).

I would like to merge this cleanup as it is and maybe introduce some check in the future.

**Review by TomasLudvik — APPROVED** [review]
If some US would be created for this - it would make me happy

**Pull request merged**
