### PR TITLE
[shopsys] disabled CSRF protection in logout actions

### LINKED ISSUE #769: 403 when trying to logout after my session expires
Reported by @stanoMilan 
### What is happening
I am logged customer on FE. When my session expires (can be reproduced manually by deleting the `PHPSESSID` cookie), I am logged out automatically in the background. Then, when I click on "Logout" (without refreshing the page before), I get an error - "403 - invalid CSRF token".

Notes: 
* probably connected to #315 
* @stanoMilan has some information about a fix that was already done on one of our internal projects.

### Expected result

I (as a logged customer) do not see any error when trying to logout. The fact, that I was logged out automatically before should not cause the application to crash.

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| fixes #769 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by pk16011990** [comment]
CSRF protection on logout is for security... Logout action without CSRF can be triggered by attacker. User is forced login again and write user's password.

Please, do not remove this security feature!

**Comment by s3tezsky** [comment]
Actually it has no added value. It may be concerned only as a security through obscurity.

This protection will not prevent any phising (which may be done via poor designed email), man in the middle and sniffing comunitaction in case it will not be running through secured conenction and even any XSS.

**Comment by henzigo** [comment]
@s3tezsky Maybe this page can help you to understand how you can create security issue with this PR ... https://security.stackexchange.com/questions/62769/should-login-and-logout-action-have-csrf-protection

**Comment by s3tezsky** [comment]
I'm closing it as it will be totally user unfriendly and annoying without it.

**Pull request closed without merging**
