### PR TITLE
responsivity of admin layout

### PR DESCRIPTION
**Pull request by kulincz**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Responsive side menu behavior (hide / show)
|New feature| Yes 
|BC breaks| Yes/No 
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes/No

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
@LukasHeinz is this waiting for something? :slightly_smiling_face: What is the state of the task? Does it need review/tests/validation?

**Comment by MattCzerner** [comment]
We should decide what to do with this PR, it will be much harder in time to get this to master, since it is like 200 commits behind from current master.

**Comment by MattCzerner** [comment]
@LukasHeinz

**Comment by PetrHeinz** [comment]
@LukasHeinz: I think we should close it if it's not going to be merged. Even then it can be accessed, serve as an inspiration or even be reopened.

**Comment by boris-brtan** [comment]
what about this PR?

**Comment by boris-brtan** [comment]
Hi @tomshopsys & @DavidOstrozlik ,
have you used or will you use something from this PR in admin-facelift? Or this PR is going to be closed and branch deleted?

**Comment by PetrHeinz** [comment]
I'm closing this stale issue as it clearly isn't getting merged anytime soon...

**Pull request closed without merging**
