### PR TITLE
Remove zoopy.cz from reference

### PR DESCRIPTION
**Pull request by sspooky13**
| Q             | A
| ------------- | ---
|Description, reason for the PR| As you can see on https://www.zoopy.cz/, this eshop is blocked. I think it's not good reference link to dysfunctional eshop. Judge yourself.
|New feature| No
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by boris-brtan** [comment]
duplicate of #894

**Comment by boris-brtan** [comment]
THX for the notice, we will push this further.

**Comment by sspooky13** [comment]
Oh sorry, I don't know it's duplicate. Then I close this PL.

**Comment by boris-brtan** [comment]
list of sites built on framework was updated and it is already in master

**Pull request closed without merging**
