### PR TITLE
[shopsys] update npm packages to latest version

### PR DESCRIPTION
**Pull request by topolanekmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| This pull request update npm packages to its latest version. 
|New feature| No
|BC breaks| No
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by grossmannmartin** [comment]
Hi @topolanekmartin,
thanks for the update, unfortunately, build fails on these updated dependencies on `eslint-check` phing target. 

Seems like there are some new rules for javascript. Can you please revise them?
If they're valid, please apply them and if not make them ignored.

Thanks

**Comment by PetrHeinz** [comment]
Hi @topolanekmartin, nice to see that npm packages are being updated :slightly_smiling_face: 

Could you include an upgrade note explaining how to update the packages when users of Shopsys Framework update to the next version, as the `package.json` file is in the open-box part?

**Comment by grossmannmartin** [comment]
Hi, I rebased branch for you.

**Comment by topolanekmartin** [comment]
Hi @grossmannmartin, thank you for review, test and rebase.

**Comment by topolanekmartin** [comment]
By this pull request was reduced total amount of vulnerabilities from 13 (12 moderate, 1 low) to 5 (4 moderate, 1 low). Current vulnerabilities are caused by packages lodash, static-eval and underscore.string. 
In order to remove vulnerabilities is needed to update version of dependency packages _tt2eot_, _tt2woff_, _svg2ttf_ and _underscore.string_ of package **grunt-webfont** (this is currently in progress, please visit https://github.com/sapegin/grunt-webfont/pull/389) and also is needed to update version of _static-module_, dependency package of the **cwise** package. Cwise is used in dependency of **grunt-spritesmith** package (this is also in progress, please visit this PR https://github.com/scijs/cwise/pull/25).
For more information please visit this issue https://github.com/shopsys/shopsys/issues/756.

**Comment by grossmannmartin** [comment]
I just add that **no new** vulnerabilities are introduced in this PR.

**Pull request merged**
