### PR TITLE
[framework] admin: display real name of logged user instead of icon

### PR DESCRIPTION
**Pull request by PetrHeinz**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Displaying real name of logged administrator in the account menu (upper right corner) makes much more sense than just displaying an icon.
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by henzigo** [comment]
What about to display name with icon ? O.o

**Comment by PetrHeinz** [comment]
@henzigo Well, I thought about the exact same thing but there should be no icon according to the design of admin face-lift:

image

Maybe we can reconsider? @LukasHeinz

Also, the color should be more subtle - I guess that's something @tomshopsys will do after this PR gets merged.

**Comment by PetrHeinz** [comment]
I've managed to make it look like this:
image

Can you please take a look on it @tomshopsys? Thx!

**Comment by tomshopsys** [comment]
I just split modification for future use. Now we can use dropdown with icon and with grey text separately.

**Comment by PetrHeinz** [comment]
@PatrikBajer I've fixed that in #1227 as it is a separate issue, thx for noticing. Is this PR OK otherwise?

**Pull request merged**
