### PR TITLE
[shopsys] Implemented styles for external docs site

### PR DESCRIPTION
**Pull request by topolanekmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| By this PR I want to add new styles for external documentation site.
|New feature| No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No
|Fixes issues| ...
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
Hi @grossmannmartin and @topolanekmartin, I have rebased the branch onto `7.3`, push-forced it and retargeted the PR to speed up the process :innocent:

**Comment by vitek-rostislav** [comment]
Hi, the danger admotion is styled weird...
Screenshot from 2019-10-20 23-25-40

And also, the menu does not look good (I see something like a misplaced hoover efect) but for some reason, it looks ok on a screenshot :thinking: :laughing:

**Comment by topolanekmartin** [comment]
Hello @vitek-rostislav,
I update styles for the danger box (please see https://www.screencast.com/t/6xG40efGN).
Is it okay for you now? :)

**Comment by vitek-rostislav** [comment]
Hi @topolanekmartin, I do not want to be a nitpick, but I would say, that "danger" box should use red colors, not yellow - it is styled this way originally (see eg. current http://docs.shopsys.com/en/8.0/cookbook/basic-data-import/). It would be awesome if you changed it this way :pray: :innocent:

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav,
Actually, danger admonition was truly changed to red in 45c271c (see around line 342)

**Pull request merged**
