### PR TITLE
[shopsys] added BlankLineBeforeStatementFixer for ensuring empty line before statements

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| This PR adds fixer to ensure empty line before: break, continue, declare, do, for, foreach, if, return, switch, throw, try, while and yield
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Review by grossmannmartin — CHANGES_REQUESTED** [review]
rules should not be in `packages/product-feed-heureka/easy-coding-standard.yml` or it's a mistake?

**Review by grossmannmartin — APPROVED** [review]
👍  awesome

**Review by sslt — APPROVED** [review]

**Review by grossmannmartin — APPROVED** [review]
nice work. Can you please check the failing build? 
Maybe we should make this change blocked by replacing FunctionLengthSniff with one that ignores whitespace. Just a thought

**Comment by TomasLudvik** [comment]
> nice work. Can you please check the failing build?
> Maybe we should make this change blocked by replacing FunctionLengthSniff with one that ignores whitespace. Just a thought

I have replaced it

**Review by pk16011990 — APPROVED** [review]

**Pull request merged**
