### PR TITLE
[project-base] PHP-FPM pool configuration now can be changed

### PR DESCRIPTION
**Pull request by grossmannmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| The default values for PHP-FPM pool configuration are fine for development, but it usually need some changes for a production server. This PR allows changing the configuration to suits the needs of a production server. Values in a file were left to the default values as it's tied to the target server specification. Purpose of this PR is to provide a way how to change the configuration, not introduce the best production settings.
|New feature| Yes 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by PetrHeinz** [comment]
I do understand your intention, but the upgrade notes don't really cover the fact that the file should be customized for the actual production-use scenario.

As a regular user, assuming from the upgrade notes you've written, it looks like all the work has been done for me but, ignoring the comments, the actual 430-lines-long config file read just this:
````
[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 
```

At least, please provide a link to the docs of nginx and an upgrade note to inspect the docs and prepare the config for a production environment (if not prepared already).

Also, what about native installation? Is there some native-only task to do?

**Comment by PetrHeinz** [comment]
And also, assuming this PR contains a non-BC-breaking bugfix, it should be rebased and retargeted to `7.3`,  as per our [Guidelines for PR](https://github.com/shopsys/shopsys/blob/master/docs/contributing/guidelines-for-pull-request.md#note-about-targeting-pull-requests), right?

**Comment by PetrHeinz** [comment]
Ad native installation) The config file is not even used. This might introduce problems as well.

**Comment by grossmannmartin** [comment]
> @grossmannmartin And also, assuming this PR contains a non-BC-breaking bugfix, it should be rebased and retargeted to `7.3`, as per our [Guidelines for PR](https://github.com/shopsys/shopsys/blob/master/docs/contributing/guidelines-for-pull-request.md#note-about-targeting-pull-requests), right?

From my PoV, it's more a new feature than bugfix. Let's let PO decide.

**Comment by grossmannmartin** [comment]
> Ad native installation) The config file is not even used. This might introduce problems as well.

Native installation is not covered in this PR intentionally. Natively installed php have the config file that can be altered and this PR is to allow to change the values for PHP running in Docker on production server.

**Pull request merged**
