### PR TITLE
[shopsys] postgresql.conf is now used by Postgres

### PR DESCRIPTION
**Pull request by TomasLudvik**
- solution found in https://github.com/docker-library/postgres/issues/105

| Q             | A
| ------------- | ---
|Description, reason for the PR| I found out, that changing configuration in postgresql.conf and restarting container had no effect. After some searching I found this solution that repair that problem.
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| ... 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
Hi Tom, thanks for the PR, I will make sure it is processed in the current or the upcoming sprint (ie. within 2 weeks) :wink:

**Comment by boris-brtan** [comment]
Hello guys @TomasLudvik and @vitek-rostislav ,
i think we would need to somehow solve this case also for k8s deployment from [deployment/postgres](https://github.com/shopsys/shopsys/blob/master/project-base/kubernetes/deployments/postgres.yml)

**Comment by TomasLudvik** [comment]
> Hello guys @TomasLudvik and @vitek-rostislav ,
> i think we would need to somehow solve this case also for k8s deployment from [deployment/postgres](https://github.com/shopsys/shopsys/blob/master/project-base/kubernetes/deployments/postgres.yml)

Hello @boris-brtan,

I am sorry, I do not understand kubernetes and I do not know how to solve it there. Please do not postpone this PR by some other things that would be nice to do.

**Comment by boris-brtan** [comment]
> > Hello guys @TomasLudvik and @vitek-rostislav ,
> > i think we would need to somehow solve this case also for k8s deployment from [deployment/postgres](https://github.com/shopsys/shopsys/blob/master/project-base/kubernetes/deployments/postgres.yml)
> 
> Hello @boris-brtan,
> 
> I am sorry, I do not understand kubernetes and I do not know how to solve it there. Please do not postpone this PR by some other things that would be nice to do.

I am sorry but otherwise we will not be able to test it.
But don't be sad it should be the same principle as with the docker-compose.yml.dist

**Comment by boris-brtan** [comment]
@TomasLudvik original command is `docker-entrypoint.sh postgres`, dont forget to update it in your project.

**Pull request merged**
