### PR TITLE
[framework] Firing opening subcategories menu animation only once

### LINKED ISSUE #833: Administration: flashing menu
### What is happening
Left menu flashs when the admin switching subsection.

### Expected result
Please fix flashing.

### PR DESCRIPTION
**Pull request by topolanekmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| By this pull request is added changes that fire opening subcategories menu animation only once. It will not be fired by clicking on every subcategory item menu.
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No
|Fixes issues| closes #833
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by PetrHeinz** [comment]
Hi @topolanekmartin, thanks for the fix! What kind of BC break do you see in here?

**Comment by topolanekmartin** [comment]
Hello @PetrHeinz, I think it is because of changing the behavior of the javascript function used in administration. What do you think?

**Comment by grossmannmartin** [comment]
Hi, @topolanekmartin, I tried it too and I see the problem as well.
With this commit, you fixed flashing "after click", but after page load menu still flashes.

**Comment by topolanekmartin** [comment]
Hello, @vitek-rostislav , @grossmannmartin, I thought this function is desirable - firing animation when page is loaded or main category was opened. I follow the description of issue where is written _"Administration: The left menu flashes when the admin switching subsection."_

But I understand that the description of the issue can be misleading. Should I fix it even when the page is reloaded? :)

**Comment by PetrHeinz** [comment]
@vitek-rostislav @topolanekmartin Personally, I wouldn't consider this a BC break because the behavior is just fixed, not changed in any meaningful way (I cannot imagine anyone would rely on `.open` being added *after* the element is shown, not before).

**Pull request merged**
