### PR TITLE
remove unused route "front_category_panel"

### PR DESCRIPTION
**Pull request by pk16011990**
| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| ... 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
Hi @pk16011990, thanks for the PR and please accept my apologies for the very very late response, I must have missed it :confused: 

You removed the route but not removed the controller action nor twig template, why?

**Comment by pk16011990** [comment]
Action in controller is still used in twig via `render(controller(...))`...

**Comment by PetrHeinz** [comment]
Hi @pk16011990 and thanks for the PR! Providing a route to the panelAction makes little sense - I see no reason to load the entire panel though AJAX and `CurrentCategoryResolver` depends on the panel being accessed as a subrequest to resolve the current open category. So I agree the route should be deleted.

I'd say this should not be considered a BC break, even though our BC promise says that *"Routes may be changed or removed only in a `MAJOR` release."* in section *Routing*. The routing configuration that has been changed is in `shopsys/project-base` so it will not affect users that upgrade.

That said, an upgrade note is missing:
```markdown
- remove the useless route `front_category_panel` from your `routing_front.yml ` ([#1042](https://github.com/shopsys/shopsys/pull/1042))
    - you'll find the configuration file in `src/Shopsys/ShopBundle/Resources/config/`
```

**Comment by boris-brtan** [comment]
rebased and added upgrade notes

**Comment by boris-brtan** [comment]
rebased and resolved conflicts in upgrade notes

**Comment by DavidOstrozlik** [comment]
Because this is a BC break, this PR should be targeted to branch 8.0 not master.  Please change and rebase it to 8.0.

**Comment by PetrHeinz** [comment]
@DavidOstrozlik See https://github.com/shopsys/shopsys/pull/1042#issuecomment-500308801 for a explanation why I think it should not be considered a BC break.

**Comment by DavidOstrozlik** [comment]
@PetrHeinz sorry i didn't see it. OK please change the description of this PR

**Pull request merged**
