### PR TITLE
[shopsys] allow to extend Translation* entities

### LINKED ISSUE #718: Extending of *Translation entities is not possible
### What is happening
I am trying to extend TransportTranslation entity using https://github.com/shopsys/shopsys/blob/master/docs/wip_glassbox/entity-extension.md#factories documentation. 

##### I have created entity `TransportTranslation` in ShopBundle:
```
<?php
namespace Shopsys\ShopBundle\Model\Transport;
use Doctrine\ORM\Mapping as ORM;
use Shopsys\FrameworkBundle\Model\Transport\TransportTranslation as BaseTransportTranslation;
/**
 * @ORM\Table(name="transport_translations")
 * @ORM\Entity
 */
class TransportTranslation extends BaseTransportTranslation
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $productDetailName;
    /**
     * @return string
     */
    public function getProductDetailName()
    {
        return $this->productDetailName;
    }
    /**
     * @param string $productDetailName
     */
    public function setProductDetailName($productDetailName)
    {
        $this->productDetailName = $productDetailName;
    }
}
```

##### I have registered extended entity in `parameters_common.yml`
```
shopsys.entity_extension.map:
    Shopsys\FrameworkBundle\Model\Transport\TransportTranslation: Shopsys\ShopBundle\Model\Transport\TransportTranslation
```

##### I have updated ShopBundle Transport so it looked like this:
```
<?php
namespace Shopsys\ShopBundle\Model\Transport;
use Doctrine\ORM\Mapping as ORM;
use Prezent\Doctrine\Translatable\Annotation as Prezent;
use Shopsys\FrameworkBundle\Model\Transport\Transport as BaseTransport;
use Shopsys\FrameworkBundle\Model\Transport\TransportData as BaseTransportData;
/**
 * @ORM\Table(name="transports")
 * @ORM\Entity
 */
class Transport extends BaseTransport
{
    /**
     * @var \Shopsys\ShopBundle\Model\Transport\TransportTranslation[]
     *
     * @Prezent\Translations(targetEntity="Shopsys\ShopBundle\Model\Transport\TransportTranslation")
     */
    protected $translations;
    /**
     * @param \Shopsys\ShopBundle\Model\Transport\TransportData $transportData
     */
    public function __construct(BaseTransportData $transportData)
    {
        parent::__construct($transportData);
    }
    /**
     * @param \Shopsys\ShopBundle\Model\Transport\TransportData $transportData
     */
    public function edit(BaseTransportData $transportData)
    {
        parent::edit($transportData);
    }
    /**
     * @return \Shopsys\ShopBundle\Model\Transport\TransportTranslation
     */
    protected function createTranslation()
    {
        return new TransportTranslation();
    }
}
```
#### What happened
```
Shopsys Framework > db-check-mapping:

Checking ORM mapping...
14:24:59 ERROR     [app] Doctrine\ORM\Mapping\MappingException: Duplicate definition of column 'locale' on entity 'Shopsys\ShopBundle\Model\Transport\TransportTranslation' in a field or discriminator column mapping. (uncaught exception) at /var/www/html/vendor/shopsys/doctrine-orm/lib/Doctrine/ORM/Mapping/MappingException.php line 575 while running console command `shopsys:migrations:check-mapping` ["exception" => Doctrine\ORM\Mapping\MappingException { …}]
14:24:59 ERROR     [console] Error thrown while running command "shopsys:migrations:check-mapping". Message: "Duplicate definition of column 'locale' on entity 'Shopsys\ShopBundle\Model\Transport\TransportTranslation' in a field or discriminator column mapping." ["exception" => Doctrine\ORM\Mapping\MappingException { …},"command" => "shopsys:migrations:check-mapping","message" => "Duplicate definition of column 'locale' on entity 'Shopsys\ShopBundle\Model\Transport\TransportTranslation' in a field or discriminator column mapping."]
14:24:59 ERROR     [app] Command `shopsys:migrations:check-mapping` exited with status code 1

In MappingException.php line 575:
                                                                                                                                                           
  [Doctrine\ORM\Mapping\MappingException]                                                                                                                  
  Duplicate definition of column 'locale' on entity 'Shopsys\ShopBundle\Model\Transport\TransportTranslation' in a field or discriminator column mapping.  
```

### Expected result
It should not throw any error.

#### I have forked `EntityExtensionParentMetadataCleanerEventSubscriber` and updated condition in `loadClassMetadata` method like this:
```
if ($this->entityNameResolver->resolve($entityName) !== $entityName
    && !StringHelper::endsWith($entityName, 'Translation')
) {
```

#### In services.yml:
```
Shopsys\FrameworkBundle\Component\EntityExtension\EntityExtensionParentMetadataCleanerEventSubscriber:
        class: Shopsys\ShopBundle\Component\EntityExtension\EntityExtensionParentMetadataCleanerEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, priority: 10 }
```

#### Created class StringHelper with a method:
```
/**
 * @param string $haystack
 * @param string $needle
 * @return bool
 */
public static function endsWith(string $haystack, string $needle): bool
{
    $expectedPosition = mb_strlen($haystack) - mb_strlen($needle);

    return mb_strrpos($haystack, $needle, 0) === $expectedPosition;
}
```

### PR DESCRIPTION
**Pull request by grossmannmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Should resolve problem when it's not possible to extend Translation* entities.
|New feature| No 
|BC breaks| No 
|Fixes issues| closes #718 
|Standards and tests pass| No
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by TomasLudvik** [comment]
Hello @simara-svatopluk,

only reason we need `EntityExtensionParentMetadataCleanerEventSubscriber` is the Gedmo tree. 

I suggest three possible way to go (in order from the most attractive to the least):
- we find reason why Gedmo needs mappedSuperclass to be extensible and solve that
- we will set mappedSuperclass only for entities that use Gedmo
- we will use this hotfix (less desirable)

We could have some little talk about this to decide that.

**Comment by simara-svatopluk** [comment]
Thanks for response.
1. I already tried to understand what is going on. I spent couple of hours on it. So I don't want to search for the reason anymore. If anyone else want, I'm not against it :+1: (but it will probably take some time, so the planned effort should be discussed with our Product Owner and we should set a maximum time limit).
2. I already implemented that solution and during code review we decided that current solution is easier to understand.

**Comment by simara-svatopluk** [comment]
So we are implementing the hotfix. We'll try to figure out better, long-term, solution - but it will be out of this PR

**Comment by simara-svatopluk** [comment]
This branch was merged to master manually. I pushed branches in wrong order, so Github didn't realize the merge happend

**Pull request closed without merging**
