### PR TITLE
Code quality configuration for Codeac.io

### PR DESCRIPTION
**Pull request by michal-simon**
Hello Shopsys team,
I briefly looked up your repo and saw a good amount of work you have done over here. Good job, guys! 🥇

You recently also tried [Codeac.io](https://www.codeac.io?utm_campaign=shopsys/shopsys) and you probably haven't had the best experience just because of lack of correct configuration.

I added configuration for Terraform, Kubernetes, PHP and ignored all 3rd party dependencies from the analysis so Codeac.io knows where your HCL/TF and YAML files live. We can not run the analysis on any random YAML files because it needs to know the root path to the "project folder". In the config file, you can, therefore, specify which paths contain Kubernetes projects and which not. I hope this will be helpful for you and find Codeac more useful after this. We are continuously improving the analysis support so it will be very helpful if you can share any challenges you are facing during writing your Infrastructure as Code as well as the app.

| Q             | A
| ------------- | ---
|Description, reason for the PR| Configuration for Codeac.io code quality analysis
|New feature| No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| Ignoring 3rd party dependencies for analysis
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

Let me know if you need any more help.

Michal Šimon
CEO @ [Codeac.io](https://www.codeac.io?utm_campaign=shopsys/shopsys)

PS: Keep doing open-source, please! We all appreciate your work a lot! :)

### CODE REVIEW

**Comment by sslt** [comment]
Hello Michal, thanks for this PR.We are considering to implement Codeac.io tool in near future. However, currently we have more pressing issues in front of us and my best estimate for processing your PR is beginning of Q2 2020. Please be patient, your contribution is not forgotten. :)

Have a good day

**Comment by michal-simon** [comment]
Thank you very much for your quick response @sslt.

I did my best to make this PR as a no-brainer for you guys as possible so you can see the right metrics. I totally understand you guys are busy, however, this PR does **not contain any breaking changes** and since the integration with Codeac.io is already active, it will be very beneficial to have a useful history of relevant matrices once you get some room for coming back to it.

I also had a discussion with a few folks from your team on some meetups and they were interested in checking our analyses out.

Thank you and happy code reviews! :)

**Comment by michal-simon** [comment]
This is a great reminder, thank you @Stale!

Is there any progress @sslt on this issue, please? Is there anything else I can help you with? 

Thank you,
Michal

**Comment by TomasLudvik** [comment]
Hi @michal-simon, I have enabled codeac for this repository and after that rebased this PR on current master, but I cannot see this PR nowhere in codeac or codeac analysis in this PR. 

We decided to take about a week to test it, if it has added value for us or not, so I am looking forward, how it will go :)

**Comment by michal-simon** [comment]
Hi Tomáš, I am glad to hear you are giving Codeac a try! In the UI are shown only PRs that have been created after the webhook so any new PR will be automatically analyzed. If you are interested into analyzing exact one we are happy to kick off the analysis retrospectively.
My colleague Jiři already reached to you to schedule a quick call where we would like to show you full power of Codeac and a little bit more extra which we are planning to release in the very near future.
Happy code reviews!

**Comment by TomasLudvik** [comment]
Hello @michal-simon, I have rebased one of my new PR on this to test configuration of Codeac and there is a lot of problems right now (https://app.codeac.io/github/shopsys/shopsys/commits/d26d8ba929f6028e47dc15f860984fd1eee4cec2). I understand it is due to many changes in our codebase since you created this PR. I am afraid that I am not currently able to fix / set everything right now. I also keep in mind your offer about informative call so we might get in touch in the future.

If there is way to enable Codeac analysis for this PR, so we do not need to test it in new one, it would be appreciated.

**Comment by TomasLudvik** [comment]
One more thing - is there way to enable Codeac analysis only for PR that include `.codeac.yml` in their root? We manage to have PRs for older versions of Shopsys etc. and it would be inconvenient to have unsuccessful analysis for such PR.

**Comment by michal-simon** [comment]
Hi Tom,
I am sorry it took me a while. We had to dig a little bit deeper than expected. For some reason, sadly, it looks like Codeac has no longer access to analyze Shopsys core repository. It looks like it was revoked on GitHub or something. It is very easy to fix but I was not able to perform retroactively any analysis on your branch.

Anyway, I synced my fork with the latest changes and adjusted the configuration a little bit again. The easiest way, how you can see the results is in my fork [https://app.codeac.io/github/michal-simon/shopsys](https://app.codeac.io/github/michal-simon/shopsys).

Also, we are working on support for PHPStan right now which I realized you are heavily using. I enabled an early version of PHPStan analysis in this commit as well. Your code is compliant with PHPStan so there are no visible results but it was successfully validated too. Twig and many other analyzers are also in our roadmap if you are interested. :)

**Comment by TomasLudvik** [comment]
Hello @michal-simon, thank you very much for your work. I have stopped Codeac analysis because many new PRs was failing on it. That is why I asked, if it is possible to run Codeac only for PRs with its configuration in root - is it? 

Link you have provided shows Page not found, so I cannot see any results.

**Comment by michal-simon** [comment]
I am sorry, I shared a bad link. This new link for the detail of the commit is definitely publically visible: https://app.codeac.io/github/michal-simon/shopsys/commits/1b7562ba3ee52b34bfea9126cb5587aa1a15be55

I also invited you as a collaborator to my fork so you should be able to see also the dashboard and everything related. I hope this is the easiest option for you to digest what is Codeac about. :)

**Comment by TomasLudvik** [comment]
Hello @michal-simon, I have added restrictions to not run codeac by default on `master` and `7.3` branches. I have also reinstated codeac rights to access our repositories and enabled webhook again.

**Comment by michal-simon** [comment]
Hi Tomas, this is great news!
So I prepared in this branch several other configuration files, do you want me to align the branch with the latest changes, or are you planning to incorporate it yourself? Is there anything else we can help with? :)

**Comment by sslt** [comment]
Hello Michal, 
we haven't forgotten about this PR, however currently it has lower priority than other tasks, please be patient we will get back to you as soon as possible. 
Thank you for your time and efforts, it will not go to waste. :)

**Comment by michal-simon** [comment]
Thank you @sslt for the update! Looking forward to hearing from you. :)

**Comment by sslt** [comment]
Hello @michal-simon, we have decided not to accept your PR as per our email conversation. We might get back to you in the future. Thank you kindly for your efforts.

**Comment by michal-simon** [comment]
Hey, thank you for letting me know. Looking forward to getting back in touch in the future. :)

**Pull request closed without merging**
