### PR TITLE
[FW-1706] Refactoring of various error-related matters on SF

### PR DESCRIPTION
**Pull request by sebaholesz**
| Q             | A
| ------------- | ---
|Description, reason for the PR| This PR mainly aims to improve how we work with status codes and how we understand error handling. 
|New feature| No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

----
:globe_with_meridians: Live Preview:
  - https://sh-serverside-error-codes.odin.shopsys.cloud
  - https://cz.sh-serverside-error-codes.odin.shopsys.cloud

### CODE REVIEW

**Review by tvikito — APPROVED** [review]

**Comment by vitek-rostislav** [comment]
Feedback from testing:

- [ ] `resolve-friendly-url` script can hypothetically return any return code so I suggest taking this into account in `middleware.ts` - I would respect the returned code and pass it in `MIDDLEWARE_STATUS_CODE_KEY`. For 4XX codes, it can still return the message 'Friendly URL page not found' 
- [ ] `middleware.ts` - It is not safe to pass the `JSON.stringify(e)` in the `MIDDLEWARE_STATUS_MESSAGE_KEY` header as it might expose sensitive data. I would rather use the `logException` function.
- [ ] `middleware.ts` - the `JSON.stringify(e)` piece of code mentioned above does not work as expected - in the logs, I see just `Middleware runtime error ({}})` - but this should be probably resolved by the point above
- [ ] It would be nice to describe the `logException` function in the documentation and motivate developers to use it

**Review by vitek-rostislav — CHANGES_REQUESTED** [review]
Feedback from testing:

- [x] `resolve-friendly-url` script can hypothetically return any return code so I suggest taking this into account in `middleware.ts` - I would respect the returned code and pass it in `MIDDLEWARE_STATUS_CODE_KEY`. For 4XX codes, it can still return the message 'Friendly URL page not found' 
- [x] `middleware.ts` - It is not safe to pass the `JSON.stringify(e)` in the `MIDDLEWARE_STATUS_MESSAGE_KEY` header as it might expose sensitive data. I would rather use the `logException` function.
- [x] `middleware.ts` - the `JSON.stringify(e)` piece of code mentioned above does not work as expected - in the logs, I see just `Middleware runtime error ({}})` - but this should be probably resolved by the point above
- [x] It would be nice to describe the `logException` function in the documentation and motivate developers to use it

**Review by tvikito — APPROVED** [review]

**Comment by vitek-rostislav** [comment]
Hi, @sebaholesz, thanks for the fixes :ok_hand: I noticed one more thing that might be addressed (but I do not insist on that, I suggest you discuss this with @pk16011990. We have the following code in `_error.tsx`:
```
const ErrorPage: NextPage<ErrorPageProps> = ({ hasGetInitialPropsRun, err, statusCode }): ReactElement => {
    if (!hasGetInitialPropsRun && err) {
        logException(err);
    }

    return statusCode === 404 ? <Error404Content /> : <Error500Content />;
};
```

That means, even 410 errors (which now can be returned from the middleware) will be rendered as 500 error page. So the page currently looks like this:
image

It is essential to mention that the HTTP code is correctly set to 410.
For me, a good enough solution would be:
```diff
- return statusCode === 404 ? <Error404Content /> : <Error500Content />;
+ const notFoundStatusCodes = [404, 410];
    
+ return notFoundStatusCodes.includes(statusCode) ? <Error404Content /> : <Error500Content />;
```

However, the question is, what about the other status codes, do we want to care about them? :slightly_smiling_face:

**Review by pk16011990 — APPROVED** [review]

**Review by pk16011990 — CHANGES_REQUESTED** [review]
missing upgrade notes

**Review by pk16011990 — APPROVED** [review]

**Review by vitek-rostislav — APPROVED** [review]

**Pull request merged**
