### PR TITLE
Stop generate url for unsafe route 'fp_js_form_validator.check_unique_entity'

### PR DESCRIPTION
**Pull request by pk16011990**
Log sometimes contains (It is reported by error reporting):

```
[2018-06-07 13:17:39] request.INFO: Matched route "admin_login". {"route":"admin_login","route_parameters":{"_controller":"Shopsys\\ShopBundle\\Controller\\Admin\\LoginController::loginAction","_route":"admin_login"},"request_uri":"https://example.com/admin/","method":"GET"} []
[2018-06-07 13:17:39] security.DEBUG: Read existing security token from the session. {"key":"_security_administration","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-06-07 13:17:39] security.WARNING: Username could not be found in the selected user provider. {"username":null,"provider":"Shopsys\\ShopBundle\\Model\\Administrator\\Security\\AdministratorUserProvider"} []
[2018-06-07 13:17:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-07 13:17:40] app.DEBUG: Router Symfony\Bundle\FrameworkBundle\Routing\Router was unable to generate route. Reason: 'Route 'fp_js_form_validator.check_unique_entity' not found': Unable to generate a URL for the named route "fp_js_form_validator.check_unique_entity" as such route does not exist. [] []
[2018-06-07 13:17:40] app.DEBUG: Router Shopsys\ShopBundle\Component\Router\CurrentDomainRouter was unable to generate route. Reason: 'Route 'fp_js_form_validator.check_unique_entity' not found': None of the chained routers were able to generate route: Route 'fp_js_form_validator.check_unique_entity' not found [] []
```

It is caused by remove unsafe route `fp_js_form_validator.check_unique_entity` to configuration of js validation.

| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| No
|BC breaks| No
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

I did not update CHANGELOG.md, I did not know link to this futured pull request :( I am demotivated about updating of it twice (befor pull request and after their creating...)

### CODE REVIEW

**Comment by pk16011990** [comment]
@stale you dont want my fix? Something is wrong with it? Sorry I dont understand it without human response on my PR...

Thx for Thumbs up reactions and stale label... 👎

**Comment by PetrHeinz** [comment]
Hi @pk16011990, thanks for the PR. Sorry for such a late response.

@stale helps us by warning us about such stale issues and PRs - when and issue or PR is still relevant we can take a look at it and move it forward, when it's obsolete it's automatically closed.

I've taken a look at the change you're suggesting and I'm a bit hesitant to approve this way of fixing it.

The original method `createJsConfigModel` looks like this: 
```php
    public function createJsConfigModel()
    {
        $result = array();
        if (!empty($this->config['routing'])) {
            foreach ($this->config['routing'] as $param => $value) {
                try {
                    $result['routing'][$param] = $this->generateUrl($value);
                } catch (\Exception $e) {
                    $result['routing'][$param] = null;
                }
            }
        }
        $model          = new JsConfig;
        $model->routing = $result['routing'];

        return $model;
    }
```

I see a problem in removing the try-catch block altogether, as it would now fail if any of the routes were unable to be generated.

Also, the reason behind the method overriding is not apparent from the code.

What come s to my mind is overriding the `generateUrl` method instead and throwing an exception when trying to generate that particular route. This approach would avoid calling the router and thus prevent the debug notice being logged. Everything else later on would behave exactly the same as now.

```php
    protected function generateUrl($route)
    {
        if ($route === 'fp_js_form_validator.check_unique_entity') {
            $message = 'Unable to generate a URL for the named route "' . $route . '" as such route was removed as unsafe.';
            throw new \Symfony\Component\Routing\Exception\RouteNotFoundException($message);
        }

        return parent::generateUrl($route);
    }
```

What do you think about this alternative approach?

Also, such a change should be mentioned in the changelog under section shopsys/framework - fixed.

**Comment by vitek-rostislav** [comment]
Hi Peter, please accept my apologies, stale-bot automatically adds the `stale` label to issues and pull requests that have no activity for 60 days...we are still fine-tuning the process of work with pull requests, and we did not get to this PR due to other priorities. But I'll take care of it soon, I promise :wink:

**Comment by pk16011990** [comment]
I dont know how it works with RouteNotFoundException (I didnt test it - is it logged?) and it is possible that it could be better solution.

It was the suggestion of a possible solution, but I do not care about how it will be fixed.

**Comment by boris-brtan** [comment]
any update on this thing?

**Comment by PetrHeinz** [comment]
@boris-brtan - if I understood Petr correctly, he doesn't want to be involved in this PR anymore. If we want to merge it, we should decide whether process my notes from https://github.com/shopsys/shopsys/pull/298#issuecomment-418275033 and test it.

**Comment by simara-svatopluk** [comment]
@pk16011990 we just closed this PR as the solution in #712 was merged to master

**Pull request closed without merging**
